import scrapy
from scrapy import Spider
from scrapy.selector import Selector
from supermarche.items import SupermarcheItem

from scrapy.http import HtmlResponse

class SupermarcheSpider(Spider):
	name="supermarche"
	allowed_domains = []
	#urls = ["http://www.750g.com/recettes_plats.htm?page="+str(x) for x in range(2,2186)]
	start_urls = ["http://courses.carrefour.fr/drive/tous-les-rayons/fruits-et-legumes/fruits/PID0/1785471",
	"http://courses.carrefour.fr/drive/tous-les-rayons/fruits-et-legumes/legumes/PID0/1785457",
	"http://courses.carrefour.fr/drive/tous-les-rayons/fruits-et-legumes/fruits-secs-et-legumes-secs/PID0/1785470",
	"http://courses.carrefour.fr/drive/tous-les-rayons/viandes-et-poissons/rotisserie/PID0/1890458",
	"http://courses.carrefour.fr/drive/tous-les-rayons/viandes-et-poissons/boucherie/PID0/1785554",
	"http://courses.carrefour.fr/drive/tous-les-rayons/viandes-et-poissons/volaille/PID0/1785551",
	"http://courses.carrefour.fr/drive/tous-les-rayons/viandes-et-poissons/poissonnerie/PID0/1785563",
	"http://courses.carrefour.fr/drive/tous-les-rayons/pains-et-patisserie/boulangerie/PID0/1785573",
	"http://courses.carrefour.fr/drive/tous-les-rayons/pains-et-patisserie/viennoiserie/PID0/1785574",
	"http://courses.carrefour.fr/drive/tous-les-rayons/pains-et-patisserie/patisserie/PID0/1785575",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/beurres-et-margarines/PID0/1785213",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/cremes-fraiches/PID0/1785188",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/oeufs/PID0/1785197",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/lait-et-boissons-lactees/PID0/1785205",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-a-la-coupe/PID0/1785178",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-d-hiver/PID0/1785187",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/camemberts-coulommiers-et-bries/PID0/1785173",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-de-caractere/PID0/1879060",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-rapes/PID0/1785174",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-enfants/PID0/1785175",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/roqueforts-et-bleus/PID0/1785176",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/chevres-et-brebis/PID0/1785177",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/gruyeres-et-comtes/PID0/1785184",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/gruyeres-et-comtes/PID0/1785184",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-a-tartiner/PID0/1785185",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/fromages/fromages-en-tranches-pour-salade-et-aperitif/PID0/1785186",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-nature-et-fromages-blancs/PID0/1785204",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-aux-fruits-et-aromatises/PID0/1785199",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-enfants/PID0/1785200",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-a-boire/PID0/1785201",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-sante-et-minceur/PID0/1785202",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/yaourts/yaourts-bio-et-soja/PID0/1785203",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/desserts/cremes-desserts/PID0/1785193",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/desserts/mousses-et-liegeois/PID0/1785194",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/desserts/flans-riz-et-semoule/PID0/1785195",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/desserts/desserts-patissiers/PID0/1785196",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/compotes-fraiches/PID0/1785211",
	"http://courses.carrefour.fr/drive/tous-les-rayons/cremerie/jus-de-fruits-frais/PID0/1785212",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/charcuterie-a-la-coupe/PID0/1785093",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/foies-gras-rillettes-et-pates/PID0/1785092",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/jambons-blancs/PID0/1785097",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/jambons-de-volaille/PID0/1785098",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/jambons-crus-et-charcuterie-tranchee/PID0/1785099",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/lardons-et-des/PID0/1785100",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/knacks/PID0/1785101",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/saucisses-et-boudins/PID0/1785102",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/charcuterie/saucissons/PID0/1785103",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/saveurs-d-asie/PID0/2047958",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/traiteur-traditionnel/PID0/1785074",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/aperitif-dinatoire/PID0/1785080",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/crudites-et-taboules/PID0/1785081",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/snacks-croques-et-galettes/PID0/1785082",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/plats-cuisines-et-soja/PID0/1785083",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/pizza-et-quiches/PID0/1785071",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/cordons-bleus-et-nuggets/PID0/1785072",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/pates-fraiches-et-gnocchis/PID0/1785073",
	"http://courses.carrefour.fr/drive/tous-les-rayons/charcuterie-traiteur/traiteur/pates-a-tartes/PID0/1785079",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/aperitifs-entrees-et-snacks/PID0/1785225",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/pizzas-et-tartes/PID0/1785237",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/plats-cuisines/PID0/1785243",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/legumes-et-frites/PID0/1785221",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/steaks-haches/PID0/1785235",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/panes-et-volailles/PID0/1785236",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/poissons/PID0/1785238",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/patisseries-surgelees/PID0/1785218",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/glaces/cremes-glacees-et-sorbets-en-bac/PID0/1785230",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/glaces/pots-de-glace/PID0/1785231",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/glaces/cones-et-batonnets/PID0/1785232",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/glaces/barres-glacees/PID0/1785233",
	"http://courses.carrefour.fr/drive/tous-les-rayons/surgeles/glaces/glaces-enfant/PID0/1785234",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pour-l-aperitif/chips/PID0/1785313",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pour-l-aperitif/biscuits-aperitif/PID0/1785314",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pour-l-aperitif/cacahuetes-pistaches-/PID0/1785315",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pour-l-aperitif/olives-et-tartinables/PID0/1785316",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/soupes-et-croutons/briques/PID0/1785287",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/soupes-et-croutons/soupes-deshydratees/PID0/1785288",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/soupes-et-croutons/croutons-et-accompagnements/PID0/1785289",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/plats-individuels/PID0/1785306",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/raviolis-et-pates/PID0/1785302",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/couscous-et-taboules/PID0/1785303",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/cassoulets/PID0/1785304",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/cassoulets/PID0/1785304",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/les-plats-cuisines/choucroutes-petits-sales-etc-/PID0/1785305",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/mais-asperges-palmiers-/PID0/1785281",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/ratatouilles-et-legumes-cuisines/PID0/1785282",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/champignons-et-tomates/PID0/1785283",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/flageolets-et-legumes-secs/PID0/1785284",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/petits-pois-et-jardinieres/PID0/1785278",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/haricots-verts-et-legumes-verts/PID0/1785279",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-legumes/salsifis-marrons-et-autres-legumes/PID0/1785280",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-poisson/thon/PID0/1785274",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-poisson/sardines-et-maquereaux/PID0/1785275",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/conserves-de-poisson/autres-conserves-de-la-mer/PID0/1785276",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/conserves/pates-et-foies-gras/PID0/1785285",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/pates-longues-spaghettis-tagliatelles-etc-/PID0/1785292",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/pates-longues-spaghettis-tagliatelles-etc-/PID0/1785292",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/pates-courtes-coquillettes-tortis-etc-/PID0/1785293",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/pates-a-farcir-lasagnes-canellonis-etc-/PID0/1785294",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/pates-cuisson-rapide/PID0/1785295",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pates-et-sauces-pour-les-pates/sauces-pour-les-pates/PID0/1785291",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/riz-puree-ble-et-semoule/riz/PID0/1785250",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/riz-puree-ble-et-semoule/sachets-express/PID0/1785251",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/riz-puree-ble-et-semoule/purees/PID0/1785252",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/riz-puree-ble-et-semoule/ble-semoule-et-legumes-secs/PID0/1785253",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/huiles-d-olive/PID0/1785266",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/huile-tournesol-friture-/PID0/1785268",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/vinaigres/PID0/1785270",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/vinaigrettes-et-jus-de-citron/PID0/1785271",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/cornichons-olives-et-condiments/PID0/1785258",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/moutardes/PID0/1785262",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/ketchup-mayonnaises-et-sauces-froides/PID0/1785263",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/burger-bbq-samourai/PID0/1785264",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/sauces-pour-les-pates-et-le-riz/PID0/1785265",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/concentres-et-coulis-de-tomate/PID0/1785267",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/huiles-vinaigres-condiments-et-sauces/bechamels-et-sauces-a-napper/PID0/1785269",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/epices-et-aides-culinaires/sel-et-poivre/PID0/1785308",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/epices-et-aides-culinaires/epices-et-herbes/PID0/1785309",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/epices-et-aides-culinaires/bouillons-et-fonds-de-sauce/PID0/1785310",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/epices-et-aides-culinaires/fecule-et-chapelure/PID0/1785311",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/pains-de-mie/PID0/1785254",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/produits-du-monde/mediterranee/PID0/1785298",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/produits-du-monde/tex-mex-et-usa/PID0/1785299",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/produits-du-monde/asie/PID0/1785300",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-salee/produits-du-monde/halal/PID0/1785297",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/tablettes-chocolat-au-lait-et-blanc/PID0/1785375",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/tablettes-chocolat-noir/PID0/1785376",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/tablettes-chocolat-patissier/PID0/1785377",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/tablettes-chocolat-patissier/PID0/1785377",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/confiseries-chocolatees/PID0/1785378",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/bonbons/PID0/1785381",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/bonbons-et-chocolats/chewings-gums-et-confiseries-de-poche/PID0/1785383",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/cereales-enfants/PID0/1785322",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/cereales-adultes/PID0/1785323",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/mueslis-et-avoines/PID0/2203708",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/barres-cereales/PID0/1785324",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/biscuits-petit-dejeuner/PID0/1785325",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/assortiment-viennoiseries/PID0/1785326",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/biscottes-pains-grilles-et-galettes/PID0/1785327",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/pain-de-mie/PID0/1785328",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/viennoiseries/PID0/2203709",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/confitures/PID0/1785329",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/petit-dejeuner/pates-a-tartiner-et-miels/PID0/1785319",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/cafes-moulus-et-en-grains/PID0/1785348",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/cafes-dosettes/PID0/1785350",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/cafes-solubles-et-capuccinos/PID0/1785343",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/filtres-et-detartrants/PID0/1785344",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/thes/PID0/1785345",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/infusions/PID0/1785346",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/chocolats-en-poudre/PID0/1785347",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/cafes-et-thes/laits-en-poudre-et-concentres/PID0/1785349",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/biscuits-au-chocolat-ou-a-la-vanille/PID0/1785367",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/biscuits-aux-fruits/PID0/1785357",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/biscuits-petit-dejeuner/PID0/1785358",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/cookies/PID0/1785359",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/petits-beurres-et-biscuits-secs/PID0/1785360",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/assortiment-de-biscuits-et-miniardises/PID0/1785361",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/barres-de-cereales-et-chocolatees/PID0/1785362",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/barres-de-cereales-et-chocolatees/PID0/1785362",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/madeleines/PID0/1785363",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/quatre-quarts-et-pains-d-epices/PID0/2203714",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/marbre-et-brownies/PID0/2203715",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/marbre-et-brownies/PID0/2203715",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/gouters-pockets/PID0/2203716",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/biscuits-et-gateaux/biscuits-bio-et-dietetiques/PID0/1785366",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/compotes-fruits-au-sirop-et-cremes-desserts/compotes/PID0/1785333",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/compotes-fruits-au-sirop-et-cremes-desserts/fruits-au-sirop/PID0/1785334",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/compotes-fruits-au-sirop-et-cremes-desserts/cremes-dessert/PID0/1785335",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/sucres-farines-et-preparation-gateaux/sucres-et-edulcorants/PID0/1785337",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/sucres-farines-et-preparation-gateaux/farines/PID0/1785338",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/sucres-farines-et-preparation-gateaux/preparation-pour-gateaux-et-flans/PID0/1785339",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/sucres-farines-et-preparation-gateaux/aide-a-la-patisserie/PID0/1785340",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/sans-gluten/PID0/1785370",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/biscuits-galettes-et-cereales/PID0/2203721",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/boissons/PID0/2203722",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/thes-et-infusions/PID0/2203719",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/edulcorants/PID0/2203720",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/repas-minceur-et-barres/PID0/1785371",
	"http://courses.carrefour.fr/drive/tous-les-rayons/epicerie-sucree/dietetique/complements-alimentaires/PID0/1785372",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/eaux/PID0/1785594",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/laits/PID0/2182158",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-d-orange/PID0/1785628",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-de-pamplemousse-agrumes/PID0/2182175",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-multifruits/PID0/1785629",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-de-pommes-et-raisins/PID0/1785624",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/ananas-et-autres-jus-de-fruits/PID0/1785625",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/formats-pockets/PID0/1785626",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-de-tomates-et-legumes/PID0/1785627",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/jus-de-fruits/jus-de-fruits-frais/PID0/2182176",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/colas-et-boissons-gazeuses/PID0/1785589",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/boissons-aux-fruits-et-thes-glaces/PID0/1785630",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/bordeaux-et-sud-ouest/PID0/1785610",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/vallee-du-rhone/PID0/1785611",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/bourgogne-et-beaujolais/PID0/1785612",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/languedoc-provence-et-autres/PID0/1785613",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/languedoc-provence-et-autres/PID0/1785613",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-rouges/vins-de-pays-et-vins-de-table-rouge/PID0/2182170",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-blancs/PID0/1785599",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-roses/PID0/1785605",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/fontaines-a-vin/PID0/2182169",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/cave-a-vins/vins-etrangers/PID0/2182171",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/champagnes-et-vins-petillants/PID0/1785633",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/bieres-blondes-rafraichissantes/PID0/1785584",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/bieres-blanches-et-aromatisees/PID0/1785585",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/bieres-de-degustation/PID0/1785586",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/bieres-sans-alcool-et-panaches/PID0/1785587",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/cidres/PID0/1785588",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/bieres-et-cidres/futs-pression/PID0/2182166",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/whisky/PID0/1785621",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/pastis-anises/PID0/1785622",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/vin-doux-portos-amers/PID0/1785615",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/rhums/PID0/1785616",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/vodkas-gins-et-tequila/PID0/1785617",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/punch-et-cocktails/PID0/1785618",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/liqueurs-et-digestifs/PID0/1785619",
	"http://courses.carrefour.fr/drive/tous-les-rayons/boissons-et-cave-a-vins/aperitifs-et-alcools/aperitifs-sans-alcool/PID0/1785620"
	]



	def parse(self, response):
		self.log('parsing details of: %s' % response.url)
		
		try:
			hxs = Selector(response)
			#open items
			item = SupermarcheItem()
			#collect 
			marques = hxs.xpath("//body/div[@id='allContainer']/div[@id='cf-main']/div[@id='Frame1']/div[@id='cf-mainWrap1']/div[@id='cf-mainWrap2']/div[@id='cf-mainWrap3']/div[@id='cf-mainWrap4']/div[@id='sub-main']/div[@class='gridTwoLeft']/div[@class='wrapper clearfix']/div[@class='content']/div[@class='content t-zone']/div[@class='table productList']/ul/li[@class='product']/div[@class='productWrap  ']/div[@class='productHead']/h3/a/span/text()").extract()
			quantites = hxs.xpath("//body/div[@id='allContainer']/div[@id='cf-main']/div[@id='Frame1']/div[@id='cf-mainWrap1']/div[@id='cf-mainWrap2']/div[@id='cf-mainWrap3']/div[@id='cf-mainWrap4']/div[@id='sub-main']/div[@class='gridTwoLeft']/div[@class='wrapper clearfix']/div[@class='content']/div[@class='content t-zone']/div[@class='table productList']/ul/li[@class='product']/div/div[@class='productMain clearfix']/div[@class='specs priceSpecs']/span[@class='unit']/text()").extract()

			for i in range(len(marques)):
				item['marque'] = marques[i]
				item['quantite'] = quantites[i]
				yield item	

		except AttributeError:
			self.log('No data to extract from : %s' % response.url)